### ISSUE TITLE
Wrap words with hyphenation in textareas

### ISSUE THREAD

**Issue by gongcastro** [NeuroDevCo/babylab-redcap#69]
Use hyphenation to break words in text area input fields:

```css
textarea {
  word-wrap: break-word;
  -webkit-hyphens: auto;
  -moz-hyphens: auto;
  -ms-hyphens: auto;
  hyphens: auto;
}
```
